Feature/edit zenvia provider
vocedm/novu pull request #3
Opened 2023-08-28 16:52 UTC by leonardovocedm

### What change does this PR introduce?

Add support SMS/WHATSAPP via request in novu.

### Why was this change needed?

Send notification via request novu.

### Other information (Screenshots)

[Mission Control #52](https://github.com/vocedm/missioncontrol/issues/52)

2023-08-28 16:56 UTC, Fernando-Erd requested changes

2023-08-28 16:56 UTC, Fernando-Erd commented on providers/zenvia/src/lib/zenvia.provider.spec.ts
> +          text: 'Teste',
troca por 'test', já que o projeto inteiro do novu esta em inglês. Que ai ele não vai reclamar de spellcheck

2023-08-28 16:56 UTC, Fernando-Erd commented on providers/zenvia/src/lib/zenvia.provider.spec.ts
> +          text: 'Teste',
Trocar por test tbm

2023-08-28 16:56 UTC, Fernando-Erd commented on providers/zenvia/src/lib/zenvia.provider.spec.ts
> +          text: 'Teste',
trocar por test

2023-08-28 16:56 UTC, Fernando-Erd commented on providers/zenvia/src/lib/zenvia.provider.spec.ts
> +          text: 'Teste',
trocar por test

2023-08-28 17:00 UTC, leonardovocedm commented on providers/zenvia/src/lib/zenvia.provider.spec.ts
> +          text: 'Teste',
Feito!

2023-08-28 17:00 UTC, leonardovocedm commented on providers/zenvia/src/lib/zenvia.provider.spec.ts
> +          text: 'Teste',
Feito!

2023-08-28 17:00 UTC, leonardovocedm commented on providers/zenvia/src/lib/zenvia.provider.spec.ts
> +          text: 'Teste',
Feito!

2023-08-28 17:00 UTC, leonardovocedm commented on providers/zenvia/src/lib/zenvia.provider.spec.ts
> +          text: 'Teste',
Feito!

2023-08-28 17:01 UTC, Fernando-Erd approved these changes

2023-08-28 20:45 UTC, victorvcruz approved these changes

2023-08-30 20:08 UTC, cristiano-andrade approved these changes

2023-08-30 20:08 UTC, cristiano-andrade approved these changes

2023-08-30 20:09 UTC, merged